name: ros-base-armhf
version: '1.0'
grade: stable
confinement: strict
summary: ROS Base Snap
description: Contains roscore and basic ROS utilities for armhf platform

slots:
  # Consumers will need to access the PYTHONPATH as well as various libs
  # contained in this snap, so share the entire $SNAP, not just the ROS
  # workspace.
  ros-base-armhf:
    content: ros-base-armhf-v1
    interface: content
    read: [/]

parts:
  ros-base-armhf:
    plugin: catkin
    rosdistro: kinetic
    include-roscore: true
    catkin-packages: []